### ISSUE TITLE
404 Not Found: kaine119.github.io/oh23-macropad

### ISSUE THREAD

**Issue by Interpause** [kaine119/kaine119.github.io#1]
Hello, if you remember me from the openhouse (& night fiesta), I bought one of your macropads. However, I was too hasty and have no idea how to remap the keys on this thing. So I took it apart to try and figure it out. However, the Github page printed on the PCB is missing. Could I have some help please?

BTW, nice rickroll on your profile README, that was fun to solve.

**Comment by Interpause** [comment]
I carelessly flashed it with `adafruit_macropad_via.uf2` from https://www.caniusevia.com/docs/download_firmware without figuring out how to backup the firmware and now its broken :(

**Comment by Interpause** [comment]
For anyone who comes across this, follow https://learn.adafruit.com/using-qmk-on-rp2040-microcontrollers/overview. Also, can follow https://www.caniusevia.com/docs/configuring_qmk to be able to remap via the VIA webapp.

**Comment by kaine119** [comment]
my bad, i haven't had time to write the page LMAO, i'll get on it asap

**Comment by Interpause** [comment]
Took a while but I managed to actually reflash it with QMK to `Esc`, `Z` and `X`. The VIA didnt work though, apparently the you need to PR them with metadata about your keyboard.

**Comment by kaine119** [comment]
Alright I've put up a [quick document](https://kaine119.github.io/oh23-macropad), could you take a look?

The default firmware runs QMK/Vial, which grabs board layout data from the microcontroller itself, not a repository like Via does. As long as you flash the firmware, you should be able to detect it with the [Vial configurator](https://get.vial.today/download). 

You can find the included `.uf2` [here](https://github.com/kaine119/oh23-macropad/tree/master/firmware).

Sorry for the trouble!

also don't spoil the rickroll 👀

**Comment by Interpause** [comment]
> Alright I've put up a [quick document](https://kaine119.github.io/oh23-macropad), could you take a look?
> 
> The default firmware runs QMK/Vial, which grabs board layout data from the microcontroller itself, not a repository like Via does. As long as you flash the firmware, you should be able to detect it with the [Vial configurator](https://get.vial.today/download).
> 
> You can find the included `.uf2` [here](https://github.com/kaine119/oh23-macropad/tree/master/firmware).
> 
> Sorry for the trouble!
> 
> also don't spoil the rickroll 👀

Seems okay. Thanks, I didnt manage to find this Vial thing so I was wondering if I needed to reflash it every time I wanted to change keymaps lol
